// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: multistaking/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryMultiStakingLocksRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMultiStakingLocksRequest) Reset()         { *m = QueryMultiStakingLocksRequest{} }
func (m *QueryMultiStakingLocksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingLocksRequest) ProtoMessage()    {}
func (*QueryMultiStakingLocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{0}
}
func (m *QueryMultiStakingLocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingLocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingLocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingLocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingLocksRequest.Merge(m, src)
}
func (m *QueryMultiStakingLocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingLocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingLocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingLocksRequest proto.InternalMessageInfo

func (m *QueryMultiStakingLocksRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMultiStakingLocksResponse struct {
	Locks      []*MultiStakingLock `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMultiStakingLocksResponse) Reset()         { *m = QueryMultiStakingLocksResponse{} }
func (m *QueryMultiStakingLocksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingLocksResponse) ProtoMessage()    {}
func (*QueryMultiStakingLocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{1}
}
func (m *QueryMultiStakingLocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingLocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingLocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingLocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingLocksResponse.Merge(m, src)
}
func (m *QueryMultiStakingLocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingLocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingLocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingLocksResponse proto.InternalMessageInfo

func (m *QueryMultiStakingLocksResponse) GetLocks() []*MultiStakingLock {
	if m != nil {
		return m.Locks
	}
	return nil
}

func (m *QueryMultiStakingLocksResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMultiStakingLockRequest struct {
	MultiStakerAddress string `protobuf:"bytes,1,opt,name=multi_staker_address,json=multiStakerAddress,proto3" json:"multi_staker_address,omitempty"`
	ValidatorAddress   string `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryMultiStakingLockRequest) Reset()         { *m = QueryMultiStakingLockRequest{} }
func (m *QueryMultiStakingLockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingLockRequest) ProtoMessage()    {}
func (*QueryMultiStakingLockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{2}
}
func (m *QueryMultiStakingLockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingLockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingLockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingLockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingLockRequest.Merge(m, src)
}
func (m *QueryMultiStakingLockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingLockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingLockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingLockRequest proto.InternalMessageInfo

type QueryMultiStakingLockResponse struct {
	Lock  *MultiStakingLock `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Found bool              `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (m *QueryMultiStakingLockResponse) Reset()         { *m = QueryMultiStakingLockResponse{} }
func (m *QueryMultiStakingLockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingLockResponse) ProtoMessage()    {}
func (*QueryMultiStakingLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{3}
}
func (m *QueryMultiStakingLockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingLockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingLockResponse.Merge(m, src)
}
func (m *QueryMultiStakingLockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingLockResponse proto.InternalMessageInfo

func (m *QueryMultiStakingLockResponse) GetLock() *MultiStakingLock {
	if m != nil {
		return m.Lock
	}
	return nil
}

func (m *QueryMultiStakingLockResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type QueryMultiStakingUnlocksRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMultiStakingUnlocksRequest) Reset()         { *m = QueryMultiStakingUnlocksRequest{} }
func (m *QueryMultiStakingUnlocksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingUnlocksRequest) ProtoMessage()    {}
func (*QueryMultiStakingUnlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{4}
}
func (m *QueryMultiStakingUnlocksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingUnlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingUnlocksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingUnlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingUnlocksRequest.Merge(m, src)
}
func (m *QueryMultiStakingUnlocksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingUnlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingUnlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingUnlocksRequest proto.InternalMessageInfo

func (m *QueryMultiStakingUnlocksRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMultiStakingUnlocksResponse struct {
	Unlocks    []*MultiStakingUnlock `protobuf:"bytes,1,rep,name=unlocks,proto3" json:"unlocks,omitempty"`
	Pagination *query.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMultiStakingUnlocksResponse) Reset()         { *m = QueryMultiStakingUnlocksResponse{} }
func (m *QueryMultiStakingUnlocksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingUnlocksResponse) ProtoMessage()    {}
func (*QueryMultiStakingUnlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{5}
}
func (m *QueryMultiStakingUnlocksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingUnlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingUnlocksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingUnlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingUnlocksResponse.Merge(m, src)
}
func (m *QueryMultiStakingUnlocksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingUnlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingUnlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingUnlocksResponse proto.InternalMessageInfo

func (m *QueryMultiStakingUnlocksResponse) GetUnlocks() []*MultiStakingUnlock {
	if m != nil {
		return m.Unlocks
	}
	return nil
}

func (m *QueryMultiStakingUnlocksResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMultiStakingUnlockRequest struct {
	MultiStakerAddress string `protobuf:"bytes,1,opt,name=multi_staker_address,json=multiStakerAddress,proto3" json:"multi_staker_address,omitempty"`
	ValidatorAddress   string `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryMultiStakingUnlockRequest) Reset()         { *m = QueryMultiStakingUnlockRequest{} }
func (m *QueryMultiStakingUnlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingUnlockRequest) ProtoMessage()    {}
func (*QueryMultiStakingUnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{6}
}
func (m *QueryMultiStakingUnlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingUnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingUnlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingUnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingUnlockRequest.Merge(m, src)
}
func (m *QueryMultiStakingUnlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingUnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingUnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingUnlockRequest proto.InternalMessageInfo

type QueryMultiStakingUnlockResponse struct {
	Unlock *MultiStakingUnlock `protobuf:"bytes,1,opt,name=unlock,proto3" json:"unlock,omitempty"`
	Found  bool                `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (m *QueryMultiStakingUnlockResponse) Reset()         { *m = QueryMultiStakingUnlockResponse{} }
func (m *QueryMultiStakingUnlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMultiStakingUnlockResponse) ProtoMessage()    {}
func (*QueryMultiStakingUnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{7}
}
func (m *QueryMultiStakingUnlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultiStakingUnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultiStakingUnlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultiStakingUnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultiStakingUnlockResponse.Merge(m, src)
}
func (m *QueryMultiStakingUnlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultiStakingUnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultiStakingUnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultiStakingUnlockResponse proto.InternalMessageInfo

func (m *QueryMultiStakingUnlockResponse) GetUnlock() *MultiStakingUnlock {
	if m != nil {
		return m.Unlock
	}
	return nil
}

func (m *QueryMultiStakingUnlockResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type QueryBondWeightsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBondWeightsRequest) Reset()         { *m = QueryBondWeightsRequest{} }
func (m *QueryBondWeightsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBondWeightsRequest) ProtoMessage()    {}
func (*QueryBondWeightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{8}
}
func (m *QueryBondWeightsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondWeightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondWeightsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondWeightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondWeightsRequest.Merge(m, src)
}
func (m *QueryBondWeightsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondWeightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondWeightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondWeightsRequest proto.InternalMessageInfo

func (m *QueryBondWeightsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryBondWeightsResponse struct {
	Infos      []*MultiStakingCoinInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	Pagination *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBondWeightsResponse) Reset()         { *m = QueryBondWeightsResponse{} }
func (m *QueryBondWeightsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBondWeightsResponse) ProtoMessage()    {}
func (*QueryBondWeightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{9}
}
func (m *QueryBondWeightsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondWeightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondWeightsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondWeightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondWeightsResponse.Merge(m, src)
}
func (m *QueryBondWeightsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondWeightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondWeightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondWeightsResponse proto.InternalMessageInfo

func (m *QueryBondWeightsResponse) GetInfos() []*MultiStakingCoinInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *QueryBondWeightsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryBondWeightRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryBondWeightRequest) Reset()         { *m = QueryBondWeightRequest{} }
func (m *QueryBondWeightRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBondWeightRequest) ProtoMessage()    {}
func (*QueryBondWeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{10}
}
func (m *QueryBondWeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondWeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondWeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondWeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondWeightRequest.Merge(m, src)
}
func (m *QueryBondWeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondWeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondWeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondWeightRequest proto.InternalMessageInfo

func (m *QueryBondWeightRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryBondWeightResponse struct {
	Weight github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=weight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"weight"`
	Found  bool                                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (m *QueryBondWeightResponse) Reset()         { *m = QueryBondWeightResponse{} }
func (m *QueryBondWeightResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBondWeightResponse) ProtoMessage()    {}
func (*QueryBondWeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{11}
}
func (m *QueryBondWeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondWeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondWeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondWeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondWeightResponse.Merge(m, src)
}
func (m *QueryBondWeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondWeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondWeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondWeightResponse proto.InternalMessageInfo

func (m *QueryBondWeightResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type QueryValidatorMultiStakingCoinRequest struct {
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryValidatorMultiStakingCoinRequest) Reset()         { *m = QueryValidatorMultiStakingCoinRequest{} }
func (m *QueryValidatorMultiStakingCoinRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorMultiStakingCoinRequest) ProtoMessage()    {}
func (*QueryValidatorMultiStakingCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{12}
}
func (m *QueryValidatorMultiStakingCoinRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorMultiStakingCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorMultiStakingCoinRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorMultiStakingCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorMultiStakingCoinRequest.Merge(m, src)
}
func (m *QueryValidatorMultiStakingCoinRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorMultiStakingCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorMultiStakingCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorMultiStakingCoinRequest proto.InternalMessageInfo

type QueryValidatorMultiStakingCoinResponse struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryValidatorMultiStakingCoinResponse) Reset() {
	*m = QueryValidatorMultiStakingCoinResponse{}
}
func (m *QueryValidatorMultiStakingCoinResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorMultiStakingCoinResponse) ProtoMessage()    {}
func (*QueryValidatorMultiStakingCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82d174b604da394d, []int{13}
}
func (m *QueryValidatorMultiStakingCoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorMultiStakingCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorMultiStakingCoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorMultiStakingCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorMultiStakingCoinResponse.Merge(m, src)
}
func (m *QueryValidatorMultiStakingCoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorMultiStakingCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorMultiStakingCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorMultiStakingCoinResponse proto.InternalMessageInfo

func (m *QueryValidatorMultiStakingCoinResponse) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryMultiStakingLocksRequest)(nil), "multistaking.v1.QueryMultiStakingLocksRequest")
	proto.RegisterType((*QueryMultiStakingLocksResponse)(nil), "multistaking.v1.QueryMultiStakingLocksResponse")
	proto.RegisterType((*QueryMultiStakingLockRequest)(nil), "multistaking.v1.QueryMultiStakingLockRequest")
	proto.RegisterType((*QueryMultiStakingLockResponse)(nil), "multistaking.v1.QueryMultiStakingLockResponse")
	proto.RegisterType((*QueryMultiStakingUnlocksRequest)(nil), "multistaking.v1.QueryMultiStakingUnlocksRequest")
	proto.RegisterType((*QueryMultiStakingUnlocksResponse)(nil), "multistaking.v1.QueryMultiStakingUnlocksResponse")
	proto.RegisterType((*QueryMultiStakingUnlockRequest)(nil), "multistaking.v1.QueryMultiStakingUnlockRequest")
	proto.RegisterType((*QueryMultiStakingUnlockResponse)(nil), "multistaking.v1.QueryMultiStakingUnlockResponse")
	proto.RegisterType((*QueryBondWeightsRequest)(nil), "multistaking.v1.QueryBondWeightsRequest")
	proto.RegisterType((*QueryBondWeightsResponse)(nil), "multistaking.v1.QueryBondWeightsResponse")
	proto.RegisterType((*QueryBondWeightRequest)(nil), "multistaking.v1.QueryBondWeightRequest")
	proto.RegisterType((*QueryBondWeightResponse)(nil), "multistaking.v1.QueryBondWeightResponse")
	proto.RegisterType((*QueryValidatorMultiStakingCoinRequest)(nil), "multistaking.v1.QueryValidatorMultiStakingCoinRequest")
	proto.RegisterType((*QueryValidatorMultiStakingCoinResponse)(nil), "multistaking.v1.QueryValidatorMultiStakingCoinResponse")
}

func init() { proto.RegisterFile("multistaking/v1/query.proto", fileDescriptor_82d174b604da394d) }

var fileDescriptor_82d174b604da394d = []byte{
	// 911 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0x04, 0x1c, 0xda, 0x17, 0x01, 0xed, 0x60, 0x81, 0x6b, 0x8a, 0x9d, 0xda, 0x4a, 0xea,
	0x16, 0xbc, 0x53, 0x1b, 0x41, 0x05, 0x25, 0x20, 0x92, 0x00, 0xe2, 0x47, 0x04, 0xac, 0x09, 0x48,
	0x5c, 0xa2, 0xb5, 0x3d, 0xd9, 0xac, 0x62, 0xcf, 0x38, 0xbb, 0x6b, 0x87, 0x28, 0xf2, 0x05, 0x09,
	0x89, 0x1b, 0x48, 0xf9, 0x03, 0x88, 0xb8, 0x20, 0x71, 0xce, 0x0d, 0x71, 0x45, 0x39, 0xa1, 0x10,
	0x2e, 0x88, 0x43, 0x84, 0x12, 0x0e, 0xf0, 0x5f, 0x20, 0xcf, 0xcc, 0xfa, 0xc7, 0xae, 0xed, 0x5d,
	0x4b, 0xe1, 0xd0, 0x53, 0x32, 0x33, 0xef, 0xbd, 0xef, 0xfb, 0xde, 0x7c, 0x3b, 0x4f, 0x86, 0x67,
	0x1b, 0xad, 0xba, 0x6b, 0x39, 0xae, 0xb1, 0x6d, 0x31, 0x93, 0xb4, 0x8b, 0x64, 0xa7, 0x45, 0xed,
	0x3d, 0xad, 0x69, 0x73, 0x97, 0xe3, 0x27, 0x07, 0x0f, 0xb5, 0x76, 0x31, 0x95, 0x30, 0xb9, 0xc9,
	0xc5, 0x19, 0xe9, 0xfe, 0x27, 0xc3, 0x52, 0x37, 0xaa, 0xdc, 0x69, 0x70, 0x67, 0x43, 0x1e, 0xc8,
	0x85, 0x3a, 0xca, 0xf9, 0xcb, 0x8b, 0xf5, 0x86, 0x57, 0x52, 0x06, 0xdd, 0x95, 0x29, 0xa4, 0x62,
	0x38, 0x54, 0xe2, 0x93, 0x76, 0xb1, 0x42, 0x5d, 0xa3, 0x48, 0x9a, 0x86, 0x69, 0x31, 0xc3, 0xb5,
	0x38, 0x53, 0xb1, 0x37, 0x4d, 0xce, 0xcd, 0x3a, 0x25, 0x46, 0xd3, 0x22, 0x06, 0x63, 0xdc, 0x15,
	0x87, 0x0a, 0x2e, 0x6b, 0xc2, 0x73, 0x1f, 0x77, 0xf3, 0xd7, 0xba, 0x28, 0x65, 0x09, 0xf2, 0x01,
	0xaf, 0x6e, 0x3b, 0x3a, 0xdd, 0x69, 0x51, 0xc7, 0xc5, 0x6f, 0x03, 0xf4, 0x4b, 0x26, 0xd1, 0x3c,
	0xca, 0xcf, 0x95, 0x16, 0x35, 0x45, 0xb9, 0x8b, 0xaf, 0x49, 0xfd, 0x0a, 0x5f, 0xfb, 0xc8, 0x30,
	0xa9, 0xca, 0xd5, 0x07, 0x32, 0xb3, 0xdf, 0x23, 0x48, 0x8f, 0x43, 0x72, 0x9a, 0x9c, 0x39, 0x14,
	0xdf, 0x87, 0x78, 0xbd, 0xbb, 0x91, 0x44, 0xf3, 0x8f, 0xe4, 0xe7, 0x4a, 0xb7, 0x34, 0x5f, 0x33,
	0x35, 0x7f, 0xaa, 0x2e, 0xe3, 0xf1, 0x3b, 0x43, 0x1c, 0x67, 0x04, 0xc7, 0xdb, 0xa1, 0x1c, 0x25,
	0xea, 0x10, 0xc9, 0x9f, 0x10, 0xdc, 0x1c, 0x49, 0xd2, 0xeb, 0xc6, 0x7b, 0x90, 0xe8, 0xdf, 0x07,
	0xb5, 0x37, 0x8c, 0x5a, 0xcd, 0xa6, 0x8e, 0x23, 0xfa, 0x72, 0x75, 0x39, 0x79, 0x7a, 0x54, 0x48,
	0x28, 0xd8, 0x37, 0xe5, 0x49, 0xd9, 0xb5, 0x2d, 0x66, 0xea, 0xb8, 0xe1, 0x15, 0xa4, 0xb6, 0x3a,
	0xc1, 0x6f, 0xc1, 0xf5, 0xb6, 0x51, 0xb7, 0x6a, 0x86, 0xcb, 0xfb, 0x85, 0x66, 0x42, 0x0a, 0x5d,
	0xeb, 0xa5, 0xa8, 0xfd, 0x57, 0xaf, 0x7c, 0x7d, 0x98, 0x89, 0xfd, 0x73, 0x98, 0x89, 0x65, 0xeb,
	0x63, 0xee, 0xb2, 0xd7, 0xe0, 0x97, 0xe0, 0xd1, 0x6e, 0xc3, 0xd4, 0x2d, 0x46, 0xe8, 0xaf, 0x08,
	0xc7, 0x09, 0x88, 0x6f, 0xf2, 0x16, 0xab, 0x09, 0x72, 0x57, 0x74, 0xb9, 0xc8, 0x5a, 0x90, 0x09,
	0xa0, 0xad, 0xb3, 0xfa, 0xff, 0xe1, 0x9d, 0x1f, 0x11, 0xcc, 0x8f, 0xc7, 0x52, 0xe2, 0x96, 0xe0,
	0xb1, 0x16, 0x1b, 0xf4, 0x4f, 0x6e, 0xa2, 0x3e, 0x99, 0xae, 0x7b, 0x39, 0x97, 0xe7, 0xa1, 0x9f,
	0x47, 0x19, 0x5d, 0xa1, 0x3d, 0x0c, 0x2e, 0x72, 0xc7, 0xde, 0x6b, 0xaf, 0xd5, 0x0f, 0x60, 0x56,
	0xb6, 0x4d, 0xdd, 0x69, 0xa4, 0x4e, 0xab, 0x94, 0x31, 0x6e, 0x32, 0xe0, 0x19, 0x81, 0xba, 0xcc,
	0x59, 0xed, 0x33, 0x6a, 0x99, 0x5b, 0xee, 0xa5, 0xbb, 0xe8, 0x10, 0x41, 0x32, 0x88, 0xd1, 0x93,
	0x14, 0xb7, 0xd8, 0x26, 0xf7, 0xbc, 0xb3, 0x30, 0x51, 0xd1, 0x0a, 0xb7, 0xd8, 0xbb, 0x6c, 0x93,
	0xeb, 0x32, 0xe7, 0xf2, 0xbc, 0xa3, 0xc1, 0xd3, 0x3e, 0x86, 0x5e, 0x13, 0x12, 0x10, 0xaf, 0x51,
	0xc6, 0x1b, 0xd2, 0x23, 0xba, 0x5c, 0x64, 0xbf, 0x42, 0x81, 0xb6, 0xf5, 0x14, 0x7d, 0x02, 0xb3,
	0xbb, 0x62, 0x47, 0xd9, 0xea, 0xb5, 0xe3, 0xb3, 0x4c, 0xec, 0xcf, 0xb3, 0xcc, 0xa2, 0x69, 0xb9,
	0x5b, 0xad, 0x8a, 0x56, 0xe5, 0x0d, 0x35, 0x79, 0xd4, 0x9f, 0x82, 0x53, 0xdb, 0x26, 0xee, 0x5e,
	0x93, 0x3a, 0xda, 0x2a, 0xad, 0x9e, 0x1e, 0x15, 0x40, 0x29, 0x58, 0xa5, 0x55, 0x5d, 0xd5, 0x1a,
	0x73, 0x7b, 0x36, 0x2c, 0x08, 0x1a, 0x9f, 0x7a, 0xb6, 0xf2, 0x77, 0xcb, 0x93, 0xf1, 0x06, 0x3c,
	0x31, 0xec, 0xd6, 0x50, 0xcf, 0x3f, 0x3e, 0x64, 0xd5, 0x01, 0x9f, 0xbe, 0x0e, 0x8b, 0x61, 0x98,
	0xaa, 0x13, 0x23, 0x7b, 0x57, 0xfa, 0xf7, 0x2a, 0xc4, 0x45, 0x01, 0xfc, 0x1d, 0x82, 0xeb, 0x81,
	0xa9, 0x84, 0xb5, 0x80, 0x05, 0x26, 0x0e, 0xca, 0x14, 0x89, 0x1c, 0x2f, 0x69, 0x65, 0xef, 0x7c,
	0xf9, 0xfb, 0xdf, 0x07, 0x33, 0x39, 0x7c, 0x8b, 0xd8, 0xd4, 0xa8, 0x5b, 0xdc, 0xa5, 0xd5, 0x2d,
	0xe2, 0x9f, 0xfe, 0xf2, 0x71, 0xfa, 0x05, 0xc1, 0x35, 0x7f, 0x21, 0x5c, 0x88, 0x06, 0xe8, 0xf1,
	0xd3, 0xa2, 0x86, 0x2b, 0x7a, 0x65, 0x41, 0x6f, 0x0d, 0xbf, 0x1f, 0x46, 0x8f, 0xec, 0x07, 0x1e,
	0xa0, 0x0e, 0xd9, 0x1f, 0xf5, 0xc0, 0x75, 0xf0, 0x0f, 0x08, 0x9e, 0x1a, 0xf1, 0x88, 0xe3, 0x7b,
	0xe1, 0xe4, 0x86, 0x67, 0x4b, 0xaa, 0x38, 0x45, 0x86, 0x52, 0xf4, 0xbc, 0x50, 0xb4, 0x80, 0x73,
	0x93, 0x14, 0x79, 0xf3, 0xe0, 0x57, 0x04, 0x38, 0x58, 0x0c, 0x93, 0xa8, 0xb0, 0x1e, 0xcf, 0x7b,
	0xd1, 0x13, 0x14, 0xcd, 0x75, 0x41, 0xf3, 0x43, 0xbc, 0x16, 0x4e, 0x73, 0x9a, 0xd6, 0xff, 0x86,
	0xe0, 0xc6, 0xd8, 0x6f, 0x05, 0xbf, 0x3c, 0x9a, 0x66, 0xd8, 0x07, 0x9d, 0xba, 0x3f, 0x75, 0x9e,
	0x52, 0xb9, 0x22, 0x54, 0x2e, 0xe1, 0x07, 0x93, 0x54, 0xf6, 0xd4, 0x15, 0xaa, 0xdc, 0x62, 0x7e,
	0xb5, 0x1d, 0xfc, 0x0d, 0x82, 0xb9, 0x81, 0xd7, 0x1c, 0xe7, 0x47, 0xb3, 0x09, 0x0e, 0x95, 0xd4,
	0x9d, 0x08, 0x91, 0xd3, 0xd8, 0x66, 0x57, 0x31, 0x38, 0x40, 0x00, 0xfd, 0x22, 0xf8, 0x76, 0x18,
	0x8c, 0xc7, 0x27, 0x1f, 0x1e, 0xa8, 0xe8, 0x94, 0x04, 0x9d, 0x17, 0xf0, 0xdd, 0x70, 0x3a, 0x64,
	0x5f, 0x3c, 0x75, 0x9d, 0xe5, 0xf2, 0xf1, 0x79, 0x1a, 0x9d, 0x9c, 0xa7, 0xd1, 0x5f, 0xe7, 0x69,
	0xf4, 0xed, 0x45, 0x3a, 0x76, 0x72, 0x91, 0x8e, 0xfd, 0x71, 0x91, 0x8e, 0x7d, 0xfe, 0xca, 0xc0,
	0x34, 0xf0, 0xd7, 0x2b, 0x78, 0x05, 0xbf, 0xf0, 0xad, 0xc5, 0x90, 0xa8, 0xcc, 0x8a, 0x5f, 0x10,
	0x2f, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xfb, 0x87, 0x0c, 0x11, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	MultiStakingLocks(ctx context.Context, in *QueryMultiStakingLocksRequest, opts ...grpc.CallOption) (*QueryMultiStakingLocksResponse, error)
	MultiStakingLock(ctx context.Context, in *QueryMultiStakingLockRequest, opts ...grpc.CallOption) (*QueryMultiStakingLockResponse, error)
	MultiStakingUnlocks(ctx context.Context, in *QueryMultiStakingUnlocksRequest, opts ...grpc.CallOption) (*QueryMultiStakingUnlocksResponse, error)
	MultiStakingUnlock(ctx context.Context, in *QueryMultiStakingUnlockRequest, opts ...grpc.CallOption) (*QueryMultiStakingUnlockResponse, error)
	ValidatorMultiStakingCoin(ctx context.Context, in *QueryValidatorMultiStakingCoinRequest, opts ...grpc.CallOption) (*QueryValidatorMultiStakingCoinResponse, error)
	BondWeights(ctx context.Context, in *QueryBondWeightsRequest, opts ...grpc.CallOption) (*QueryBondWeightsResponse, error)
	BondWeight(ctx context.Context, in *QueryBondWeightRequest, opts ...grpc.CallOption) (*QueryBondWeightResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MultiStakingLocks(ctx context.Context, in *QueryMultiStakingLocksRequest, opts ...grpc.CallOption) (*QueryMultiStakingLocksResponse, error) {
	out := new(QueryMultiStakingLocksResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/MultiStakingLocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MultiStakingLock(ctx context.Context, in *QueryMultiStakingLockRequest, opts ...grpc.CallOption) (*QueryMultiStakingLockResponse, error) {
	out := new(QueryMultiStakingLockResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/MultiStakingLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MultiStakingUnlocks(ctx context.Context, in *QueryMultiStakingUnlocksRequest, opts ...grpc.CallOption) (*QueryMultiStakingUnlocksResponse, error) {
	out := new(QueryMultiStakingUnlocksResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/MultiStakingUnlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MultiStakingUnlock(ctx context.Context, in *QueryMultiStakingUnlockRequest, opts ...grpc.CallOption) (*QueryMultiStakingUnlockResponse, error) {
	out := new(QueryMultiStakingUnlockResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/MultiStakingUnlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorMultiStakingCoin(ctx context.Context, in *QueryValidatorMultiStakingCoinRequest, opts ...grpc.CallOption) (*QueryValidatorMultiStakingCoinResponse, error) {
	out := new(QueryValidatorMultiStakingCoinResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/ValidatorMultiStakingCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BondWeights(ctx context.Context, in *QueryBondWeightsRequest, opts ...grpc.CallOption) (*QueryBondWeightsResponse, error) {
	out := new(QueryBondWeightsResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/BondWeights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BondWeight(ctx context.Context, in *QueryBondWeightRequest, opts ...grpc.CallOption) (*QueryBondWeightResponse, error) {
	out := new(QueryBondWeightResponse)
	err := c.cc.Invoke(ctx, "/multistaking.v1.Query/BondWeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	MultiStakingLocks(context.Context, *QueryMultiStakingLocksRequest) (*QueryMultiStakingLocksResponse, error)
	MultiStakingLock(context.Context, *QueryMultiStakingLockRequest) (*QueryMultiStakingLockResponse, error)
	MultiStakingUnlocks(context.Context, *QueryMultiStakingUnlocksRequest) (*QueryMultiStakingUnlocksResponse, error)
	MultiStakingUnlock(context.Context, *QueryMultiStakingUnlockRequest) (*QueryMultiStakingUnlockResponse, error)
	ValidatorMultiStakingCoin(context.Context, *QueryValidatorMultiStakingCoinRequest) (*QueryValidatorMultiStakingCoinResponse, error)
	BondWeights(context.Context, *QueryBondWeightsRequest) (*QueryBondWeightsResponse, error)
	BondWeight(context.Context, *QueryBondWeightRequest) (*QueryBondWeightResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MultiStakingLocks(ctx context.Context, req *QueryMultiStakingLocksRequest) (*QueryMultiStakingLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiStakingLocks not implemented")
}
func (*UnimplementedQueryServer) MultiStakingLock(ctx context.Context, req *QueryMultiStakingLockRequest) (*QueryMultiStakingLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiStakingLock not implemented")
}
func (*UnimplementedQueryServer) MultiStakingUnlocks(ctx context.Context, req *QueryMultiStakingUnlocksRequest) (*QueryMultiStakingUnlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiStakingUnlocks not implemented")
}
func (*UnimplementedQueryServer) MultiStakingUnlock(ctx context.Context, req *QueryMultiStakingUnlockRequest) (*QueryMultiStakingUnlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiStakingUnlock not implemented")
}
func (*UnimplementedQueryServer) ValidatorMultiStakingCoin(ctx context.Context, req *QueryValidatorMultiStakingCoinRequest) (*QueryValidatorMultiStakingCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorMultiStakingCoin not implemented")
}
func (*UnimplementedQueryServer) BondWeights(ctx context.Context, req *QueryBondWeightsRequest) (*QueryBondWeightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BondWeights not implemented")
}
func (*UnimplementedQueryServer) BondWeight(ctx context.Context, req *QueryBondWeightRequest) (*QueryBondWeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BondWeight not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MultiStakingLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultiStakingLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MultiStakingLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/MultiStakingLocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MultiStakingLocks(ctx, req.(*QueryMultiStakingLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MultiStakingLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultiStakingLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MultiStakingLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/MultiStakingLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MultiStakingLock(ctx, req.(*QueryMultiStakingLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MultiStakingUnlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultiStakingUnlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MultiStakingUnlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/MultiStakingUnlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MultiStakingUnlocks(ctx, req.(*QueryMultiStakingUnlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MultiStakingUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultiStakingUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MultiStakingUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/MultiStakingUnlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MultiStakingUnlock(ctx, req.(*QueryMultiStakingUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorMultiStakingCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorMultiStakingCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorMultiStakingCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/ValidatorMultiStakingCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorMultiStakingCoin(ctx, req.(*QueryValidatorMultiStakingCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BondWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBondWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BondWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/BondWeights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BondWeights(ctx, req.(*QueryBondWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BondWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBondWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BondWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multistaking.v1.Query/BondWeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BondWeight(ctx, req.(*QueryBondWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "multistaking.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MultiStakingLocks",
			Handler:    _Query_MultiStakingLocks_Handler,
		},
		{
			MethodName: "MultiStakingLock",
			Handler:    _Query_MultiStakingLock_Handler,
		},
		{
			MethodName: "MultiStakingUnlocks",
			Handler:    _Query_MultiStakingUnlocks_Handler,
		},
		{
			MethodName: "MultiStakingUnlock",
			Handler:    _Query_MultiStakingUnlock_Handler,
		},
		{
			MethodName: "ValidatorMultiStakingCoin",
			Handler:    _Query_ValidatorMultiStakingCoin_Handler,
		},
		{
			MethodName: "BondWeights",
			Handler:    _Query_BondWeights_Handler,
		},
		{
			MethodName: "BondWeight",
			Handler:    _Query_BondWeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multistaking/v1/query.proto",
}

func (m *QueryMultiStakingLocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingLocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingLocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingLocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingLocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingLocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Locks) > 0 {
		for iNdEx := len(m.Locks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingLockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingLockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingLockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MultiStakerAddress) > 0 {
		i -= len(m.MultiStakerAddress)
		copy(dAtA[i:], m.MultiStakerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MultiStakerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingLockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingLockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingLockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Lock != nil {
		{
			size, err := m.Lock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingUnlocksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingUnlocksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingUnlocksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingUnlocksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingUnlocksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingUnlocksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Unlocks) > 0 {
		for iNdEx := len(m.Unlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Unlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingUnlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingUnlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingUnlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MultiStakerAddress) > 0 {
		i -= len(m.MultiStakerAddress)
		copy(dAtA[i:], m.MultiStakerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MultiStakerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultiStakingUnlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultiStakingUnlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultiStakingUnlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Unlock != nil {
		{
			size, err := m.Unlock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondWeightsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondWeightsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondWeightsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondWeightsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondWeightsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondWeightsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Infos) > 0 {
		for iNdEx := len(m.Infos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Infos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondWeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondWeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondWeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondWeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondWeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondWeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryValidatorMultiStakingCoinRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorMultiStakingCoinRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorMultiStakingCoinRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddr) > 0 {
		i -= len(m.ValidatorAddr)
		copy(dAtA[i:], m.ValidatorAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorMultiStakingCoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorMultiStakingCoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorMultiStakingCoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMultiStakingLocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMultiStakingLocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Locks) > 0 {
		for _, e := range m.Locks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMultiStakingLockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MultiStakerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMultiStakingLockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Lock != nil {
		l = m.Lock.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Found {
		n += 2
	}
	return n
}

func (m *QueryMultiStakingUnlocksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMultiStakingUnlocksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Unlocks) > 0 {
		for _, e := range m.Unlocks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMultiStakingUnlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MultiStakerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMultiStakingUnlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Unlock != nil {
		l = m.Unlock.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Found {
		n += 2
	}
	return n
}

func (m *QueryBondWeightsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondWeightsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Infos) > 0 {
		for _, e := range m.Infos {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondWeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondWeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Weight.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.Found {
		n += 2
	}
	return n
}

func (m *QueryValidatorMultiStakingCoinRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorMultiStakingCoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMultiStakingLocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingLocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingLocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingLocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingLocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingLocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locks = append(m.Locks, &MultiStakingLock{})
			if err := m.Locks[len(m.Locks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingLockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingLockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingLockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiStakerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiStakerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingLockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingLockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingLockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lock == nil {
				m.Lock = &MultiStakingLock{}
			}
			if err := m.Lock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingUnlocksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingUnlocksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingUnlocksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingUnlocksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingUnlocksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingUnlocksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unlocks = append(m.Unlocks, &MultiStakingUnlock{})
			if err := m.Unlocks[len(m.Unlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingUnlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingUnlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingUnlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiStakerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiStakerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultiStakingUnlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultiStakingUnlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultiStakingUnlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Unlock == nil {
				m.Unlock = &MultiStakingUnlock{}
			}
			if err := m.Unlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondWeightsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondWeightsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondWeightsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondWeightsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondWeightsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondWeightsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Infos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Infos = append(m.Infos, &MultiStakingCoinInfo{})
			if err := m.Infos[len(m.Infos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondWeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondWeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondWeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondWeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondWeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondWeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorMultiStakingCoinRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorMultiStakingCoinRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorMultiStakingCoinRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorMultiStakingCoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorMultiStakingCoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorMultiStakingCoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
